<?php
 echo "testing";
// $productCollection = $block->getProductCollection();
// foreach ($productCollection as $product) {
//     print_r($product->getData());     
//     echo "<br>";
//}
 ?>

 <div class="grid12-9 no-gutter">

	<div class="grid12-4">
		<div class="collapsible mobile-collapsible">
			<h6 class="block-title heading">CUSTOMER CARE</h6>
			<div class="block-content">
				<ul class="bullet">
					<li><a href="https://gracewoodrow.com/free-shipping-both-way/">Free Shipping Both Way</a></li>
					<li><a href="https://gracewoodrow.com/free-35-day-returns/">Free 35-day Returns</a></li>
					<li><a href="https://gracewoodrow.com/free-90-day-resizing/">Free 90-day Resizing</a></li>
                                        <li><a href="https://gracewoodrow.com/12-months-buy-back-guarantee/">12-months Buy-Back Guarantee</a></li>
				</ul><ul class="bullet">
					<li><a href="https://gracewoodrow.com/diamond-price-match/">Diamond Price Match</a></li>
					<li><a href="https://gracewoodrow.com/lifetime-diamond-upgrade/">Lifetime Diamond Upgrade</a></li>
					<li><a href="https://gracewoodrow.com/lifetime-warranty/">Lifetime warranty</a></li>
				</ul><ul class="bullet">
						<li><a href="/shippingtracking/">Track Your Order</a></li>
				</ul>

			</div>
		</div>
	</div>

	<div class="grid12-4">
		<div class="collapsible mobile-collapsible">
			<h6 class="block-title heading">FOLLOW</h6>
			<div class="block-content">
                           <div class="social-icons-content">
                               <a href="#">
                                  <div class="follow-us  instagram-select-option">
                                  </div>
                            </a>
                            <a href="#">
                                   <div class="follow-us facebook-section-option">
                                  </div>
                            </a>
                          <a href="#">  
                                <div class="follow-us pintrest-section-option">
                                </div>
                         </a>
			<h6><strong>CHAT WITH US</strong></h6>
                               <div class="chat-link">  <p onclick="myPopupchat()">Live Chat</p></div>
                                <p>+1(206)909-7300</p>
                                <p class="link-color"><a href="#">info@gracewoodrow.com</a></p>
                      </div>
		    </div>
		</div>
	</div>

	<div class="grid12-4">
		<div class="collapsible mobile-collapsible">
			<h6 class="block-title heading">WE ACCEPT</h6>
			<div class="block-content"> 
                                    <a href="#">
                                    	<div class="we-accept-images"> </div>
                               		</a>
			</div>

		</div>
	</div>

</div>